#!/usr/bin/env node
/**
 * Compile src/prompts/**\/*.md into src/prompts/generated.ts.
 *
 * Prompt bodies live as Markdown so they're reviewable and diffable, but they
 * must reach both the Next.js server bundle and the esbuild worker bundle
 * without any loader config or runtime fs reads (neither the standalone output
 * nor worker.js ships the src/ tree). A generated TS module works everywhere.
 *
 * File contents are used verbatim — including whether they end in a newline —
 * so the seeded prompt text is byte-identical to the .md file.
 *
 *   node scripts/gen-prompts.mjs          # regenerate
 *   (src/prompts/generated.test.ts fails in CI if generated.ts is stale)
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs'
import { join, relative, sep } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

export const PROMPTS_DIR = fileURLToPath(new URL('../src/prompts/', import.meta.url))
export const OUTPUT_FILE = join(PROMPTS_DIR, 'generated.ts')

/** Map of prompt id ("system/system.main", "agents/alpha.system") → file contents. */
export function collectPrompts(dir = PROMPTS_DIR) {
  const out = {}
  const walk = d => {
    for (const name of readdirSync(d).sort()) {
      const full = join(d, name)
      if (statSync(full).isDirectory()) walk(full)
      else if (name.endsWith('.md')) {
        const id = relative(dir, full).split(sep).join('/').replace(/\.md$/, '')
        out[id] = readFileSync(full, 'utf8')
      }
    }
  }
  walk(dir)
  return out
}

export function renderModule(prompts) {
  const entries = Object.keys(prompts)
    .sort()
    .map(id => `  ${JSON.stringify(id)}: ${JSON.stringify(prompts[id])},`)
    .join('\n')
  return [
    '// GENERATED by scripts/gen-prompts.mjs from src/prompts/**/*.md — do not edit.',
    '// Edit the .md file, then run `npm run gen:prompts`.',
    '',
    'export const PROMPTS = {',
    entries,
    '} as const',
    '',
    'export type PromptId = keyof typeof PROMPTS',
    '',
  ].join('\n')
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const prompts = collectPrompts()
  writeFileSync(OUTPUT_FILE, renderModule(prompts))
  console.log(`gen-prompts: wrote ${Object.keys(prompts).length} prompts → ${relative(process.cwd(), OUTPUT_FILE)}`)
}
