apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ntopng
  namespace: monitoring
  labels:
    app: ntopng
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`ntopng.khalis.corp`)
      kind: Rule
      services:
        - name: ntopng
          port: 3000
          namespace: monitoring
