apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: <ENV_NAME>
  namespace: argocd
spec:
  description: "ORION-managed cluster: <ENV_NAME>"
  sourceRepos:
    - '<GITEA_REPO_URL>'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
