apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <ENV_NAME>-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: <ENV_NAME>
  source:
    repoURL: '<GITEA_REPO_URL>'
    targetRevision: main
    path: .
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
