/**
 * Knowledge graph embedding utilities.
 *
 * Generates vector embeddings for notes using ORION's configured embedding
 * providers (OpenAI text-embedding-3-small or Ollama nomic-embed-text).
 * Stores embeddings in PostgreSQL via pgvector for semantic search.
 *
 * Requires the pgvector PostgreSQL extension:
 *   CREATE EXTENSION IF NOT EXISTS vector;
 */

import { prisma } from './db'
import { sanitizeContextNote } from './sanitize-context'

// ── Providers ────────────────────────────────────────────────────────────────

interface EmbeddingResult {
  vector: number[]
  modelRef: string
}

async function getEmbeddingProvider(): Promise<{
  baseUrl: string
  apiKey?: string
  modelId: string
  provider: 'openai' | 'ollama'
} | null> {
  const models = await prisma.externalModel.findMany({ where: { enabled: true } })

  // OpenAI text-embedding models first
  const openai = models.find(
    (m: any) => m.provider === 'openai' && m.modelId.includes('text-embedding'),
  )
  if (openai) {
    return {
      baseUrl: openai.baseUrl,
      apiKey: openai.apiKey ?? '',
      modelId: openai.modelId,
      provider: 'openai',
    }
  }

  // Fallback: Ollama (typically nomic-embed-text or bge-m3)
  const ollama = models.find((m: any) => m.provider === 'ollama')
  if (ollama && ollama.baseUrl) {
    return {
      baseUrl: ollama.baseUrl,
      modelId: ollama.modelId,
      provider: 'ollama',
    }
  }

  return null
}

// ── Embedding Generation ─────────────────────────────────────────────────────

/**
 * Generate a text embedding using the configured provider.
 */
export async function generateEmbedding(
  text: string,
  attributeToDream: boolean = false,
): Promise<EmbeddingResult | null> {
  const provider = await getEmbeddingProvider()
  if (!provider) return null

  // Guard against SSRF via DB-controlled baseUrl
  const { isPrivateUrl } = await import('./ssrf-guard')
  if (await isPrivateUrl(provider.baseUrl)) return null

  if (provider.provider === 'openai') {
    const res = await fetch(`${provider.baseUrl}/v1/embeddings`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${provider.apiKey}`,
      },
      body: JSON.stringify({
        model: provider.modelId,
        input: text.slice(0, 8191),
        encoding_format: 'float',
      }),
      signal: AbortSignal.timeout(30_000),
    })
    if (!res.ok) return null
    const data = await res.json() as {
      data: Array<{ embedding: number[] }>
      usage?: { prompt_tokens?: number; total_tokens?: number }
    }
    if (attributeToDream) {
      const inputTokens = data.usage?.prompt_tokens ?? data.usage?.total_tokens ?? Math.ceil(Math.min(text.length, 8191) / 4)
      await recordDreamEmbeddingUsage(inputTokens, provider.modelId)
    }
    return { vector: data.data[0].embedding, modelRef: provider.modelId }
  }

  // Ollama: supports /api/embed endpoint (nomic-embed-text, bge-m3, etc.)
  const res = await fetch(`${provider.baseUrl}/api/embed`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ model: provider.modelId, input: text }),
    signal: AbortSignal.timeout(30_000),
  })
  if (!res.ok) {
    console.error(`[embeddings] Ollama /api/embed returned ${res.status} for model ${provider.modelId}`)
    return null
  }
  // NOTE: /api/embed (current) returns `embeddings` — a plural array-of-arrays,
  // one vector per input. This is NOT the same shape as the deprecated
  // /api/embeddings endpoint, which returns a singular `embedding` array.
  // Reading the wrong field silently returns `undefined`, which previously
  // got passed straight through to storeEmbedding() and corrupted the vector
  // column with no error anywhere in the pipeline.
  const data = await res.json() as { embeddings?: number[][] }
  const vector = data.embeddings?.[0]
  if (!Array.isArray(vector) || vector.length === 0) {
    console.error(
      `[embeddings] Ollama /api/embed response missing 'embeddings[0]' for model ${provider.modelId}. ` +
      `Response keys: ${Object.keys(data ?? {}).join(', ') || '(empty)'}`,
    )
    return null
  }
  // Ollama's /api/embed does not report token usage — estimate from input length.
  if (attributeToDream) {
    await recordDreamEmbeddingUsage(Math.ceil(text.length / 4), provider.modelId)
  }
  return { vector, modelRef: provider.modelId }
}

// ── Dream usage attribution ─────────────────────────────────────────────────
// Only embeddings generated by Dream's own extraction/synthesis pipeline
// (embedNote / embedAllNotes) are attributed here. Chat RAG lookups
// (retrieveKnowledgeContext, notes search) call generateEmbedding without
// attributeToDream so their spend isn't misattributed to the background
// memory-consolidation agent.
//
// Cache only positive hits — a miss (e.g. queried before ensureSystemAgents()
// has committed the Dream row on a fresh install/boot) must retry on the next
// call rather than permanently caching null for the process lifetime.
let _dreamAgentIdCache: string | null = null
async function getDreamAgentId(): Promise<string | null> {
  if (_dreamAgentIdCache !== null) return _dreamAgentIdCache
  const agent = await prisma.agent.findUnique({ where: { name: 'Dream' }, select: { id: true } })
  _dreamAgentIdCache = agent?.id ?? null
  return _dreamAgentIdCache
}

// One-time-per-process warning so a fresh install (or a worker process that
// never calls ensureSystemAgents()) doesn't silently drop Dream token
// accounting forever without any log signal.
let _dreamAgentMissingWarnedOnce = false

async function recordDreamEmbeddingUsage(inputTokens: number, modelId: string): Promise<void> {
  try {
    const dreamAgentId = await getDreamAgentId()
    if (!dreamAgentId) {
      if (!_dreamAgentMissingWarnedOnce) {
        console.warn('[dream] Dream agent not found — embedding token usage not recorded. Ensure ensureSystemAgents() has run.')
        _dreamAgentMissingWarnedOnce = true
      }
      return
    }
    const { recordTokenUsage } = await import('./token-budget')
    // Embeddings have no output tokens.
    await recordTokenUsage(dreamAgentId, null, inputTokens, 0, modelId)
  } catch (err) {
    console.error('[dream] Failed to record embedding token usage:', err)
    _dreamAgentIdCache = null  // retry lookup next time — agent may have been renamed/recreated
  }
}

/**
 * Build the text to embed: title + content, capped for token limits.
 */
function buildEmbeddingText(note: { title: string; content: string }): string {
  const combined = `${note.title}\n\n${note.content}`.trim()
  // ~20K chars is safe for most embedding models
  return combined.length > 20000 ? combined.slice(0, 20000) + '...' : combined
}

// ── Storage ──────────────────────────────────────────────────────────────────

/** Upsert an embedding for a note (replaces previous version). */
export async function storeEmbedding(
  noteId: string,
  vector: number[],
  modelRef: string,
): Promise<void> {
  if (!Array.isArray(vector) || vector.length === 0 || vector.some(v => typeof v !== 'number' || !Number.isFinite(v))) {
    // Previously an undefined/malformed vector (e.g. from the Ollama field-name
    // bug above) would be JSON.stringify()'d as "null" or "[]" and stored
    // silently, corrupting the note's embedding with no error anywhere.
    throw new Error(
      `[embeddings] storeEmbedding(${noteId}) received an invalid vector (modelRef=${modelRef}): ` +
      `${Array.isArray(vector) ? `length=${vector.length}` : typeof vector}`,
    )
  }
  await prisma.noteEmbedding.upsert({
    where: { noteId },
    update: {
      embedding: JSON.stringify(vector),
      dimension: vector.length,
      modelRef,
      version: { increment: 1 },
      updatedAt: new Date(),
    },
    create: {
      noteId,
      embedding: JSON.stringify(vector),
      dimension: vector.length,
      modelRef,
    },
  })
}

/**
 * Embed a single note: build text → generate embedding → store.
 * Returns true if embedding was generated successfully.
 */
export async function embedNote(
  note: {
    id: string
    title: string
    content: string
  },
  options?: { attributeToDream?: boolean },
): Promise<boolean> {
  const text = buildEmbeddingText(note)
  if (!text.trim()) return false

  const result = await generateEmbedding(text, options?.attributeToDream ?? false)
  if (!result) return false

  await storeEmbedding(note.id, result.vector, result.modelRef)
  return true
}

/**
 * Embed ALL notes. For initial backfill or re-embedding after a model change.
 * This is a manual backfill triggered by a human (or a one-off migration), not
 * part of Dream's own scheduled extraction/synthesis/pruning cycle — so it is
 * NOT attributed to Dream's token budget.
 */
export async function embedAllNotes(): Promise<{ embedded: number; failed: number }> {
  const notes = await prisma.note.findMany({
    select: { id: true, title: true, content: true },
  })

  let embedded = 0
  let failed = 0

  for (const note of notes) {
    try {
      const ok = await embedNote(note)
      if (ok) embedded++
      else failed++
      // Rate-limit: small delay between API calls
      await new Promise(r => setTimeout(r, 100))
    } catch (err) {
      console.error(`[embeddings] embedNote(${note.id}) failed:`, err instanceof Error ? err.message : err)
      failed++
    }
  }

  return { embedded, failed }
}

// ── Vector Search ────────────────────────────────────────────────────────────

/**
 * Vector similarity search over note embeddings.
 *
 * Uses pgvector's `<=>` cosine-distance operator, matching the HNSW index
 * (`vector_cosine_ops`, migration 7_note_embeddings_hnsw_index) and the
 * `note_embeddings` schema comment. `<->` (L2/Euclidean distance) is a
 * *different* metric — an HNSW index built with `vector_cosine_ops` cannot
 * be used to accelerate an `<->` query, and even if it could, L2 distance
 * on these vectors has no defined relationship to the 0..1 similarity
 * thresholds (`minScore`) used by every caller.
 *
 * `ORDER BY` and `LIMIT` are applied directly to the indexed distance
 * expression (`embedding <=> $vector`) so pgvector can use the ANN index.
 * Sorting on a derived column (e.g. `1 - distance`) defeats index usage
 * because the planner can no longer recognize the order-by target as the
 * indexed expression. `score` is a projected column computed from that same
 * distance, not the sort key — pgvector's cosine distance is
 * `1 - cosine_similarity`, so `1 - distance` here is a true cosine
 * similarity in [0, 1] (assuming reasonably-normalized text embeddings).
 *
 * Filters by `modelRef` so that if the configured embedding provider
 * changes, vectors from different model spaces are never compared against
 * each other (which would produce meaningless similarity scores even when
 * dimensions happen to coincide).
 *
 * @param queryVector - The embedding vector for the query
 * @param modelRef - The embedding model that produced queryVector; only
 *   note_embeddings rows from the same model are searched
 * @param limit - Maximum results to return
 * @returns Notes ranked by cosine similarity score (descending)
 */
export async function vectorSearch(
  queryVector: number[],
  modelRef: string,
  limit: number = 10,
): Promise<
  Array<{
    noteId: string
    title: string
    content: string
    type: string
    folder: string
    pinned: boolean
    score: number
  }>
> {
  const vecStr = `[${queryVector.join(',')}]`

  const results = await prisma.$queryRaw<unknown[]>`
    SELECT
      ne."noteId",
      n."title",
      n.content,
      n."type",
      n.folder,
      n.pinned,
      (1 - (ne.embedding <=> ${vecStr}::vector))::float AS score
    FROM "note_embeddings" ne
    JOIN "Note" n ON n.id = ne."noteId"
    WHERE ne.embedding IS NOT NULL
      AND ne."modelRef" = ${modelRef}
    ORDER BY ne.embedding <=> ${vecStr}::vector
    LIMIT ${limit}
  `

  return (results as any[]).map(r => ({
    noteId: r.noteId as string,
    title: r.title as string,
    content: r.content as string,
    type: r.type as string,
    folder: r.folder as string,
    pinned: Boolean(r.pinned),
    score: parseFloat(r.score as string),
  }))
}

// ── Semantic Connections ─────────────────────────────────────────────────────

/**
 * Find semantically related notes for a given note and store as edges.
 * Called after embedding to keep the graph up-to-date.
 */
export async function computeSemanticEdges(
  noteId: string,
  topN: number = 5,
): Promise<void> {
  const target = await prisma.noteEmbedding.findUnique({ where: { noteId } })
  if (!target) return

  const vecStr = target.embedding

  const similar = await prisma.$queryRaw<
    Array<{ targetNoteId: string; score: number }>
  >`
    SELECT
      other."noteId" AS "targetNoteId",
      (1 - (other.embedding <=> ${vecStr}::vector))::float AS score
    FROM "note_embeddings" other
    WHERE other."noteId" != ${noteId}
      AND other.embedding IS NOT NULL
      AND other."modelRef" IS NOT DISTINCT FROM ${target.modelRef}
    ORDER BY other.embedding <=> ${vecStr}::vector
    LIMIT ${topN}
  `

  for (const row of similar) {
    await prisma.semanticConnection.upsert({
      where: {
        sourceNoteId_targetNoteId: {
          sourceNoteId: noteId,
          targetNoteId: row.targetNoteId,
        },
      },
      update: { score: row.score },
      create: {
        sourceNoteId: noteId,
        targetNoteId: row.targetNoteId,
        score: row.score,
      },
    })
  }
}

// ── RAG Context Retrieval ─────────────────────────────────────────────────────

/**
 * Retrieve the most semantically relevant notes for a query.
 * Returns a formatted markdown block ready to append to a system prompt.
 * Returns empty string silently on any error (no embedding provider, pgvector
 * not installed, no notes embedded, etc.) so it never blocks an LLM call.
 */
// minScore thresholds below (here and at every other vectorSearch call site:
// agent-context.ts, worker.ts, tool-registry.ts) were originally calibrated
// against a broken metric — vectorSearch used to sort by L2 distance (`<->`)
// while filtering a "score" computed as `1 - <-> distance`, which is not a
// bounded similarity value at all. Now that vectorSearch uses `<=>` (cosine
// distance) with `score = 1 - cosine_distance = cosine_similarity` (bounded
// [0,1]), these thresholds are unverified against real data — no live/dev
// database with embedded Notes was reachable from this change to sanity-check
// the resulting score distribution. Left as-is intentionally rather than
// guessing new numbers; recalibrate using the admin knowledge-search page
// (added in a follow-up PR) once real query/score pairs are available.
export async function retrieveKnowledgeContext(
  query: string,
  topK = 3,
  minScore = 0.2,
): Promise<string> {
  try {
    const result = await generateEmbedding(query.slice(0, 2000))
    if (!result) return ''

    // llm-context notes are intentionally unscoped (no createdBy filter) —
    // they are system-wide context for agent prompts and must remain globally visible.
    const hits = await vectorSearch(result.vector, result.modelRef, topK)
    const relevant = hits.filter(h => h.score >= minScore)
    if (relevant.length === 0) return ''

    // Sanitize all retrieved notes before injecting into agent system prompts.
    // Previously this path applied no sanitization — dream-extracted notes and
    // any user-authored note could inject instructions via vector search.
    return relevant
      .map(h => {
        const typeTag = h.type !== 'note' ? ` [${h.type}]` : ''
        const sanitizedContent = sanitizeContextNote(h.title, h.content)
        const body = sanitizedContent.length > 1500
          ? sanitizedContent.slice(0, 1500) + '\n[…]'
          : sanitizedContent
        return `### ${h.title}${typeTag}\n${body}`
      })
      .join('\n\n')
  } catch {
    return ''
  }
}

/**
 * Compute semantic edges for ALL notes. For initial backfill.
 */
export async function computeAllSemanticEdges(topN: number = 5): Promise<{
  computed: number
  failed: number
}> {
  const embeddings = await prisma.noteEmbedding.findMany({
    select: { noteId: true },
  })

  let computed = 0
  let failed = 0

  for (const emb of embeddings) {
    try {
      await computeSemanticEdges(emb.noteId, topN)
      computed++
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      console.error(`computeSemanticEdges(${emb.noteId}) failed: ${msg}`)
      failed++
    }
  }

  return { computed, failed }
}
