/**
 * Knowledge graph embedding utilities.
 *
 * Generates vector embeddings for notes using ORION's configured embedding
 * providers (OpenAI text-embedding-3-small or Ollama nomic-embed-text).
 * Stores embeddings in PostgreSQL via pgvector for semantic search.
 *
 * Requires the pgvector PostgreSQL extension:
 *   CREATE EXTENSION IF NOT EXISTS vector;
 */

import { Prisma } from '@prisma/client'
import { prisma } from './db'
import { sanitizeContextNote } from './sanitize-context'

// ── Providers ────────────────────────────────────────────────────────────────

interface EmbeddingResult {
  vector: number[]
  modelRef: string
}

async function getEmbeddingProvider(): Promise<{
  baseUrl: string
  apiKey?: string
  modelId: string
  provider: 'openai' | 'ollama'
} | null> {
  const models = await prisma.externalModel.findMany({ where: { enabled: true } })

  // OpenAI text-embedding models first
  const openai = models.find(
    (m: any) => m.provider === 'openai' && m.modelId.includes('text-embedding'),
  )
  if (openai) {
    return {
      baseUrl: openai.baseUrl,
      apiKey: openai.apiKey ?? '',
      modelId: openai.modelId,
      provider: 'openai',
    }
  }

  // Fallback: Ollama (typically nomic-embed-text or bge-m3)
  const ollama = models.find((m: any) => m.provider === 'ollama')
  if (ollama && ollama.baseUrl) {
    return {
      baseUrl: ollama.baseUrl,
      modelId: ollama.modelId,
      provider: 'ollama',
    }
  }

  return null
}

// ── Embedding Generation ─────────────────────────────────────────────────────

/**
 * Generate a text embedding using the configured provider.
 */
export async function generateEmbedding(
  text: string,
  attributeToDream: boolean = false,
): Promise<EmbeddingResult | null> {
  const provider = await getEmbeddingProvider()
  if (!provider) return null

  // Guard against SSRF via DB-controlled baseUrl
  const { isPrivateUrl } = await import('./ssrf-guard')
  if (await isPrivateUrl(provider.baseUrl)) return null

  if (provider.provider === 'openai') {
    const res = await fetch(`${provider.baseUrl}/v1/embeddings`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${provider.apiKey}`,
      },
      body: JSON.stringify({
        model: provider.modelId,
        input: text.slice(0, 8191),
        encoding_format: 'float',
      }),
      signal: AbortSignal.timeout(30_000),
    })
    if (!res.ok) return null
    const data = await res.json() as {
      data: Array<{ embedding: number[] }>
      usage?: { prompt_tokens?: number; total_tokens?: number }
    }
    if (attributeToDream) {
      const inputTokens = data.usage?.prompt_tokens ?? data.usage?.total_tokens ?? Math.ceil(Math.min(text.length, 8191) / 4)
      await recordDreamEmbeddingUsage(inputTokens, provider.modelId)
    }
    return { vector: data.data[0].embedding, modelRef: provider.modelId }
  }

  // Ollama: supports /api/embed endpoint (nomic-embed-text, bge-m3, etc.)
  const res = await fetch(`${provider.baseUrl}/api/embed`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ model: provider.modelId, input: text }),
    signal: AbortSignal.timeout(30_000),
  })
  if (!res.ok) {
    console.error(`[embeddings] Ollama /api/embed returned ${res.status} for model ${provider.modelId}`)
    return null
  }
  // NOTE: /api/embed (current) returns `embeddings` — a plural array-of-arrays,
  // one vector per input. This is NOT the same shape as the deprecated
  // /api/embeddings endpoint, which returns a singular `embedding` array.
  // Reading the wrong field silently returns `undefined`, which previously
  // got passed straight through to storeEmbedding() and corrupted the vector
  // column with no error anywhere in the pipeline.
  const data = await res.json() as { embeddings?: number[][] }
  const vector = data.embeddings?.[0]
  if (!Array.isArray(vector) || vector.length === 0) {
    console.error(
      `[embeddings] Ollama /api/embed response missing 'embeddings[0]' for model ${provider.modelId}. ` +
      `Response keys: ${Object.keys(data ?? {}).join(', ') || '(empty)'}`,
    )
    return null
  }
  // Ollama's /api/embed does not report token usage — estimate from input length.
  if (attributeToDream) {
    await recordDreamEmbeddingUsage(Math.ceil(text.length / 4), provider.modelId)
  }
  return { vector, modelRef: provider.modelId }
}

// ── Dream usage attribution ─────────────────────────────────────────────────
// Only embeddings generated by Dream's own extraction/synthesis pipeline
// (embedNote / embedAllNotes) are attributed here. Chat RAG lookups
// (retrieveKnowledgeContext, notes search) call generateEmbedding without
// attributeToDream so their spend isn't misattributed to the background
// memory-consolidation agent.
//
// Cache only positive hits — a miss (e.g. queried before ensureSystemAgents()
// has committed the Dream row on a fresh install/boot) must retry on the next
// call rather than permanently caching null for the process lifetime.
let _dreamAgentIdCache: string | null = null
async function getDreamAgentId(): Promise<string | null> {
  if (_dreamAgentIdCache !== null) return _dreamAgentIdCache
  const agent = await prisma.agent.findUnique({ where: { name: 'Dream' }, select: { id: true } })
  _dreamAgentIdCache = agent?.id ?? null
  return _dreamAgentIdCache
}

// One-time-per-process warning so a fresh install (or a worker process that
// never calls ensureSystemAgents()) doesn't silently drop Dream token
// accounting forever without any log signal.
let _dreamAgentMissingWarnedOnce = false

async function recordDreamEmbeddingUsage(inputTokens: number, modelId: string): Promise<void> {
  try {
    const dreamAgentId = await getDreamAgentId()
    if (!dreamAgentId) {
      if (!_dreamAgentMissingWarnedOnce) {
        console.warn('[dream] Dream agent not found — embedding token usage not recorded. Ensure ensureSystemAgents() has run.')
        _dreamAgentMissingWarnedOnce = true
      }
      return
    }
    const { recordTokenUsage } = await import('./token-budget')
    // Embeddings have no output tokens.
    await recordTokenUsage(dreamAgentId, null, inputTokens, 0, modelId)
  } catch (err) {
    console.error('[dream] Failed to record embedding token usage:', err)
    _dreamAgentIdCache = null  // retry lookup next time — agent may have been renamed/recreated
  }
}

/**
 * Build the text to embed: title + content, capped for token limits.
 */
function buildEmbeddingText(note: { title: string; content: string }): string {
  const combined = `${note.title}\n\n${note.content}`.trim()
  // ~20K chars is safe for most embedding models
  return combined.length > 20000 ? combined.slice(0, 20000) + '...' : combined
}

// ── Storage ──────────────────────────────────────────────────────────────────

/** Upsert an embedding for a note (replaces previous version). */
export async function storeEmbedding(
  noteId: string,
  vector: number[],
  modelRef: string,
): Promise<void> {
  if (!Array.isArray(vector) || vector.length === 0 || vector.some(v => typeof v !== 'number' || !Number.isFinite(v))) {
    // Previously an undefined/malformed vector (e.g. from the Ollama field-name
    // bug above) would be JSON.stringify()'d as "null" or "[]" and stored
    // silently, corrupting the note's embedding with no error anywhere.
    throw new Error(
      `[embeddings] storeEmbedding(${noteId}) received an invalid vector (modelRef=${modelRef}): ` +
      `${Array.isArray(vector) ? `length=${vector.length}` : typeof vector}`,
    )
  }
  await prisma.noteEmbedding.upsert({
    where: { noteId },
    update: {
      embedding: JSON.stringify(vector),
      dimension: vector.length,
      modelRef,
      version: { increment: 1 },
      updatedAt: new Date(),
    },
    create: {
      noteId,
      embedding: JSON.stringify(vector),
      dimension: vector.length,
      modelRef,
    },
  })
}

/**
 * Embed a single note: build text → generate embedding → store.
 * Returns true if embedding was generated successfully.
 */
export async function embedNote(
  note: {
    id: string
    title: string
    content: string
  },
  options?: { attributeToDream?: boolean },
): Promise<boolean> {
  const text = buildEmbeddingText(note)
  if (!text.trim()) return false

  const result = await generateEmbedding(text, options?.attributeToDream ?? false)
  if (!result) return false

  await storeEmbedding(note.id, result.vector, result.modelRef)
  return true
}

/**
 * Embed ALL notes. For initial backfill or re-embedding after a model change.
 * This is a manual backfill triggered by a human (or a one-off migration), not
 * part of Dream's own scheduled extraction/synthesis/pruning cycle — so it is
 * NOT attributed to Dream's token budget.
 */
export async function embedAllNotes(): Promise<{ embedded: number; failed: number }> {
  const notes = await prisma.note.findMany({
    select: { id: true, title: true, content: true },
  })

  let embedded = 0
  let failed = 0

  for (const note of notes) {
    try {
      const ok = await embedNote(note)
      if (ok) embedded++
      else failed++
      // Rate-limit: small delay between API calls
      await new Promise(r => setTimeout(r, 100))
    } catch (err) {
      console.error(`[embeddings] embedNote(${note.id}) failed:`, err instanceof Error ? err.message : err)
      failed++
    }
  }

  return { embedded, failed }
}

// ── Access control ───────────────────────────────────────────────────────────

/**
 * Ownership predicate mirroring the rest of the notes API's convention (see
 * `scopeByCreatedBy` in `app/api/notes/route.ts` and `assertCanModify` in
 * `lib/auth.ts`): a note with `createdBy = NULL` is a shared/system record
 * visible to everyone; any other note is only visible to its creator.
 *
 * @param callerId - `undefined` signals a trusted/unscoped caller (service,
 *   admin, or an internal agent-driven context with no single human owner,
 *   e.g. worker.ts's background task runs or `agent-context.ts`'s room-agent
 *   pre-flight) — no filtering is applied. A string restricts results to
 *   notes owned by that user, plus unowned/shared notes — this includes
 *   `retrieveKnowledgeContext` when it's called on behalf of a specific user
 *   (e.g. the chat stream route), which still surfaces shared `llm-context`
 *   notes since those are always created with `createdBy: null`.
 */
function ownerFilterSql(callerId: string | undefined, noteAlias: string): Prisma.Sql {
  if (callerId === undefined) return Prisma.empty
  return Prisma.sql`AND (${Prisma.raw(noteAlias)}."createdBy" IS NULL OR ${Prisma.raw(noteAlias)}."createdBy" = ${callerId})`
}

/**
 * Prisma Client query-builder equivalent of `ownerFilterSql`, for callers
 * (e.g. the `knowledge_graph` tool) that build their `Note` query with the
 * Prisma Client fluent API rather than `$queryRaw`. Same semantics:
 * `undefined` callerId means trusted/unscoped (no filter — spread yields
 * nothing); a string restricts to that user's own notes plus unowned/shared
 * (`createdBy: null`) notes.
 */
export function ownerFilterWhere(callerId: string | undefined): Prisma.NoteWhereInput {
  if (callerId === undefined) return {}
  return { OR: [{ createdBy: null }, { createdBy: callerId }] }
}

// ── Vector Search ────────────────────────────────────────────────────────────

/**
 * Vector similarity search over note embeddings.
 *
 * Uses pgvector's `<=>` cosine-distance operator, matching the HNSW index
 * (`vector_cosine_ops`, migration 7_note_embeddings_hnsw_index) and the
 * `note_embeddings` schema comment. `<->` (L2/Euclidean distance) is a
 * *different* metric — an HNSW index built with `vector_cosine_ops` cannot
 * be used to accelerate an `<->` query, and even if it could, L2 distance
 * on these vectors has no defined relationship to the 0..1 similarity
 * thresholds (`minScore`) used by every caller.
 *
 * `ORDER BY` and `LIMIT` are applied directly to the indexed distance
 * expression (`embedding <=> $vector`) so pgvector can use the ANN index.
 * Sorting on a derived column (e.g. `1 - distance`) defeats index usage
 * because the planner can no longer recognize the order-by target as the
 * indexed expression. `score` is a projected column computed from that same
 * distance, not the sort key — pgvector's cosine distance is
 * `1 - cosine_similarity`, so `1 - distance` here is a true cosine
 * similarity in [0, 1] (assuming reasonably-normalized text embeddings).
 *
 * Filters by `modelRef` so that if the configured embedding provider
 * changes, vectors from different model spaces are never compared against
 * each other (which would produce meaningless similarity scores even when
 * dimensions happen to coincide).
 *
 * @param queryVector - The embedding vector for the query
 * @param modelRef - The embedding model that produced queryVector; only
 *   note_embeddings rows from the same model are searched
 * @param limit - Maximum results to return
 * @param callerId - See `ownerFilterSql`: `undefined` (default) means
 *   trusted/unscoped; pass a user id to restrict to that user's + shared notes.
 * @returns Notes ranked by cosine similarity score (descending)
 */
export async function vectorSearch(
  queryVector: number[],
  modelRef: string,
  limit: number = 10,
  callerId?: string,
): Promise<
  Array<{
    noteId: string
    title: string
    content: string
    type: string
    folder: string
    pinned: boolean
    score: number
  }>
> {
  const vecStr = `[${queryVector.join(',')}]`
  const ownerFilter = ownerFilterSql(callerId, 'n')

  const results = await prisma.$queryRaw<unknown[]>`
    SELECT
      ne."noteId",
      n."title",
      n.content,
      n."type",
      n.folder,
      n.pinned,
      (1 - (ne.embedding <=> ${vecStr}::vector))::float AS score
    FROM "note_embeddings" ne
    JOIN "Note" n ON n.id = ne."noteId"
    WHERE ne.embedding IS NOT NULL
      AND ne."modelRef" = ${modelRef}
      ${ownerFilter}
    ORDER BY ne.embedding <=> ${vecStr}::vector
    LIMIT ${limit}
  `

  return (results as any[]).map(r => ({
    noteId: r.noteId as string,
    title: r.title as string,
    content: r.content as string,
    type: r.type as string,
    folder: r.folder as string,
    pinned: Boolean(r.pinned),
    score: parseFloat(r.score as string),
  }))
}

// ── Hybrid Search (dense + keyword, fused with RRF) ─────────────────────────

export interface HybridSearchHit {
  noteId: string
  title: string
  content: string
  type: string
  folder: string
  pinned: boolean
  /** Fused Reciprocal Rank Fusion score — this is the ranking key. */
  score: number
  /** Cosine similarity [0,1], or null if this note wasn't in the vector candidate set. */
  vectorScore: number | null
  /** ts_rank_cd keyword relevance, or null if this note wasn't in the keyword candidate set. */
  keywordScore: number | null
}

// k in the RRF formula `1 / (k + rank)`. Larger k flattens the influence of
// rank differences near the top; 60 is the commonly-cited default from the
// original RRF paper (Cormack et al.) and typical hybrid-search references.
const RRF_K = 60
// How many top candidates each leg (vector / keyword) contributes before
// fusion. Wide enough that a note ranked outside the top-N of one leg can
// still surface on the strength of the other; narrow enough to keep both
// subqueries cheap.
const HYBRID_CANDIDATE_POOL = 40

export function mapHybridRows(rows: unknown[]): HybridSearchHit[] {
  return (rows as any[]).map(r => ({
    noteId: r.noteId as string,
    title: r.title as string,
    content: r.content as string,
    type: r.type as string,
    folder: r.folder as string,
    pinned: Boolean(r.pinned),
    score: parseFloat(r.score as string),
    vectorScore: r.vectorScore != null ? parseFloat(r.vectorScore as string) : null,
    keywordScore: r.keywordScore != null ? parseFloat(r.keywordScore as string) : null,
  }))
}

/**
 * Hybrid search over notes: dense pgvector cosine search + Postgres native
 * full-text search (on `Note.searchVector`, a generated tsvector column —
 * migration 20260808_note_search_vector), fused via Reciprocal Rank Fusion.
 *
 * Mirrors the InvestigationNote full-text pattern (searchNotes() in
 * app/api/monitoring/security/investigations/_utils.ts) but combines it with
 * the vector leg rather than using either alone — dense embeddings are weak
 * on exact tokens (pod names, CRD kinds, CLI flags, error strings) that
 * `websearch_to_tsquery` handles well, and keyword search is weak on
 * conceptual/paraphrased queries that embeddings handle well.
 *
 * Each leg independently ranks its own top `HYBRID_CANDIDATE_POOL` notes;
 * RRF (`score = sum(1 / (RRF_K + rank))` across legs a note appears in) fuses
 * the two rankings into one, and the top `limit` by fused score are returned.
 * `websearch_to_tsquery` (not `plainto_tsquery`) is used so callers can pass
 * quoted phrases and `-exclude` terms directly in free text.
 *
 * If no embedding provider is configured, falls back to keyword-only search
 * (vectorScore is null on every hit) rather than returning nothing.
 *
 * @param callerId - See `ownerFilterSql`: `undefined` (default) means
 *   trusted/unscoped (used by internal callers like the llm-context leg of
 *   `retrieveKnowledgeContext`); pass a user id to restrict both the
 *   keyword and vector legs to that user's own notes plus shared
 *   (createdBy IS NULL) notes — required for any user-facing entry point
 *   (the /api/notes/search route, the knowledge_search tool).
 * @returns modelRef of the embedding used (null if the vector leg was
 *   skipped), plus fused hits with both per-leg scores exposed for
 *   debugging/tuning (surfaced in the admin knowledge-search UI).
 */
export async function hybridSearch(
  query: string,
  limit: number = 10,
  callerId?: string,
): Promise<{ modelRef: string | null; hits: HybridSearchHit[] }> {
  const q = query.slice(0, 2000)
  const embedding = await generateEmbedding(q)
  const ownerFilter = ownerFilterSql(callerId, 'n')

  if (!embedding) {
    const rows = await prisma.$queryRaw<unknown[]>`
      WITH kw_top AS (
        SELECT n.id AS note_id,
               ts_rank_cd(n."searchVector", websearch_to_tsquery('english', ${q})) AS keyword_score
        FROM "Note" n
        WHERE n."searchVector" @@ websearch_to_tsquery('english', ${q})
          ${ownerFilter}
        ORDER BY ts_rank_cd(n."searchVector", websearch_to_tsquery('english', ${q})) DESC
        LIMIT ${HYBRID_CANDIDATE_POOL}
      ),
      kw AS (
        SELECT note_id, keyword_score,
               ROW_NUMBER() OVER (ORDER BY keyword_score DESC) AS rnk
        FROM kw_top
      )
      SELECT
        n.id AS "noteId", n.title, n.content, n."type", n.folder, n.pinned,
        (1.0 / (${RRF_K} + kw.rnk))::float AS score,
        NULL::float AS "vectorScore",
        kw.keyword_score::float AS "keywordScore"
      FROM kw
      JOIN "Note" n ON n.id = kw.note_id
      ORDER BY score DESC, n.id
      LIMIT ${limit}
    `
    return { modelRef: null, hits: mapHybridRows(rows) }
  }

  const vecStr = `[${embedding.vector.join(',')}]`

  const rows = await prisma.$queryRaw<unknown[]>`
    WITH vec_top AS (
      SELECT ne."noteId" AS note_id,
             (1 - (ne.embedding <=> ${vecStr}::vector)) AS vector_score
      FROM "note_embeddings" ne
      JOIN "Note" n ON n.id = ne."noteId"
      WHERE ne.embedding IS NOT NULL
        AND ne."modelRef" = ${embedding.modelRef}
        ${ownerFilter}
      ORDER BY ne.embedding <=> ${vecStr}::vector
      LIMIT ${HYBRID_CANDIDATE_POOL}
    ),
    vec AS (
      SELECT note_id, vector_score,
             ROW_NUMBER() OVER (ORDER BY vector_score DESC) AS rnk
      FROM vec_top
    ),
    kw_top AS (
      SELECT n.id AS note_id,
             ts_rank_cd(n."searchVector", websearch_to_tsquery('english', ${q})) AS keyword_score
      FROM "Note" n
      WHERE n."searchVector" @@ websearch_to_tsquery('english', ${q})
        ${ownerFilter}
      ORDER BY ts_rank_cd(n."searchVector", websearch_to_tsquery('english', ${q})) DESC
      LIMIT ${HYBRID_CANDIDATE_POOL}
    ),
    kw AS (
      SELECT note_id, keyword_score,
             ROW_NUMBER() OVER (ORDER BY keyword_score DESC) AS rnk
      FROM kw_top
    ),
    fused AS (
      SELECT
        COALESCE(vec.note_id, kw.note_id) AS note_id,
        vec.vector_score,
        kw.keyword_score,
        (COALESCE(1.0 / (${RRF_K} + vec.rnk), 0) + COALESCE(1.0 / (${RRF_K} + kw.rnk), 0))::float AS score
      FROM vec
      FULL OUTER JOIN kw ON vec.note_id = kw.note_id
    )
    SELECT
      n.id AS "noteId", n.title, n.content, n."type", n.folder, n.pinned,
      fused.score,
      fused.vector_score::float AS "vectorScore",
      fused.keyword_score::float AS "keywordScore"
    FROM fused
    JOIN "Note" n ON n.id = fused.note_id
    ORDER BY fused.score DESC, n.id
    LIMIT ${limit}
  `
  return { modelRef: embedding.modelRef, hits: mapHybridRows(rows) }
}

// ── Skill Embeddings ──────────────────────────────────────────────────────────
// Semantic trigger matching for skills, as a complement to the existing exact
// substring match on triggerPatterns (see matchAndInjectSkills in claude.ts).

/** Upsert an embedding for a skill (replaces previous version). */
export async function storeSkillEmbedding(
  nebulaId: string,
  vector: number[],
  modelRef: string,
): Promise<void> {
  if (!Array.isArray(vector) || vector.length === 0 || vector.some(v => typeof v !== 'number' || !Number.isFinite(v))) {
    // Mirror the storeEmbedding guard: a malformed vector must never be
    // silently stringified and stored, corrupting the skill's embedding.
    throw new Error(
      `[embeddings] storeSkillEmbedding(${nebulaId}) received an invalid vector (modelRef=${modelRef}): ` +
      `${Array.isArray(vector) ? `length=${vector.length}` : typeof vector}`,
    )
  }
  await prisma.nebulaEmbedding.upsert({
    where: { nebulaId },
    update: {
      embedding: JSON.stringify(vector),
      dimension: vector.length,
      modelRef,
      version: { increment: 1 },
      updatedAt: new Date(),
    },
    create: {
      nebulaId,
      embedding: JSON.stringify(vector),
      dimension: vector.length,
      modelRef,
    },
  })
}

/**
 * Embed a skill's "meaning" (name + description + trigger patterns — NOT the
 * full step-by-step instructions, which are longer and less semantically
 * distinctive) so a message describing the same situation in different words
 * can still surface it. Returns true if embedding was generated successfully.
 */
export async function embedSkill(
  skill: { id: string; name: string; description?: string; triggerPatterns?: string[] },
  options?: { attributeToDream?: boolean },
): Promise<boolean> {
  const text = [skill.name, skill.description, ...(skill.triggerPatterns ?? [])]
    .filter(Boolean)
    .join('. ')
  if (!text.trim()) return false

  const result = await generateEmbedding(text, options?.attributeToDream ?? false)
  if (!result) return false

  await storeSkillEmbedding(skill.id, result.vector, result.modelRef)
  return true
}

/**
 * Semantic similarity search over installed skills in an environment.
 * Complements the exact substring match: a message that doesn't literally
 * contain a trigger phrase can still surface a skill if it's a close enough
 * semantic match (see minScore in matchAndInjectSkills for the threshold).
 */
export async function skillVectorSearch(
  queryVector: number[],
  modelRef: string,
  environmentId: string,
  limit: number = 3,
): Promise<Array<{ nebulaId: string; score: number }>> {
  const vecStr = `[${queryVector.join(',')}]`

  // Mirrors vectorSearch: `<=>` (cosine distance) to match the
  // vector_cosine_ops HNSW index, ORDER BY on the indexed distance
  // expression (not the derived `score` column) so pgvector can use the
  // ANN index, and a modelRef filter so vectors from different embedding
  // model spaces are never compared against each other.
  const results = await prisma.$queryRaw<unknown[]>`
    SELECT
      ne."nebulaId",
      (1 - (ne.embedding <=> ${vecStr}::vector))::float AS score
    FROM "nebula_embeddings" ne
    JOIN "NebulaInstance" n ON n.id = ne."nebulaId"
    WHERE ne.embedding IS NOT NULL
      AND ne."modelRef" = ${modelRef}
      AND n."environmentId" = ${environmentId}
      AND n.category = 'skill'
      AND n."isInstalled" = true
    ORDER BY ne.embedding <=> ${vecStr}::vector
    LIMIT ${limit}
  `

  return (results as any[]).map(r => ({
    nebulaId: r.nebulaId as string,
    score: parseFloat(r.score as string),
  }))
}

// ── Semantic Connections ─────────────────────────────────────────────────────

/**
 * Find semantically related notes for a given note and store as edges.
 * Called after embedding to keep the graph up-to-date.
 */
export async function computeSemanticEdges(
  noteId: string,
  topN: number = 5,
): Promise<void> {
  const target = await prisma.noteEmbedding.findUnique({ where: { noteId } })
  if (!target) return

  const vecStr = target.embedding

  const similar = await prisma.$queryRaw<
    Array<{ targetNoteId: string; score: number }>
  >`
    SELECT
      other."noteId" AS "targetNoteId",
      (1 - (other.embedding <=> ${vecStr}::vector))::float AS score
    FROM "note_embeddings" other
    WHERE other."noteId" != ${noteId}
      AND other.embedding IS NOT NULL
      AND other."modelRef" IS NOT DISTINCT FROM ${target.modelRef}
    ORDER BY other.embedding <=> ${vecStr}::vector
    LIMIT ${topN}
  `

  for (const row of similar) {
    await prisma.semanticConnection.upsert({
      where: {
        sourceNoteId_targetNoteId: {
          sourceNoteId: noteId,
          targetNoteId: row.targetNoteId,
        },
      },
      update: { score: row.score },
      create: {
        sourceNoteId: noteId,
        targetNoteId: row.targetNoteId,
        score: row.score,
      },
    })
  }
}

// ── RAG Context Retrieval ─────────────────────────────────────────────────────

/**
 * Retrieve the most semantically relevant notes for a query.
 * Returns a formatted markdown block ready to append to a system prompt.
 * Returns empty string silently on any error (no embedding provider, pgvector
 * not installed, no notes embedded, etc.) so it never blocks an LLM call.
 */
// minScore thresholds below (here and at every other call site that filters
// on it: agent-context.ts, worker.ts, tool-registry.ts) were originally
// calibrated against a broken metric — vectorSearch used to sort by L2
// distance (`<->`) while filtering a "score" computed as `1 - <-> distance`,
// which is not a bounded similarity value at all. Now that the vector leg
// uses `<=>` (cosine distance) with `score = 1 - cosine_distance =
// cosine_similarity` (bounded [0,1]), these thresholds are unverified
// against real data — no live/dev database with embedded Notes was reachable
// from this change to sanity-check the resulting score distribution. Left
// as-is intentionally rather than guessing new numbers; recalibrate using
// the admin knowledge-search page (added in a follow-up PR) once real
// query/score pairs are available.
//
// minScore is applied to `vectorScore` (cosine similarity), NOT the fused
// RRF `score` — RRF scores live on a totally different, non-interpretable
// scale (`sum of 1/(k+rank)`, max ~0.03 for two legs at k=60), so comparing
// them against a similarity threshold like 0.2 would silently filter out
// everything.
//
// The filter keeps a hit if it has ANY keyword match (`keywordScore !== null`),
// regardless of vectorScore — including a mixed hit that appeared in BOTH legs
// with a low vectorScore. Filtering those out was the original bug here:
// `vectorScore === null` does NOT mean "matched via keyword search only" — it
// means "this note fell outside the vector leg's HYBRID_CANDIDATE_POOL", which
// is unrelated to whether it also has a keyword match. A note that ranks #1 on
// exact-token relevance but has ANY embedding (even a mediocre-similarity one,
// putting it inside the vector pool with vectorScore !== null) was being
// wrongly dropped by the old `h.vectorScore === null` check, while the exact
// same note with no embedding at all (vectorScore stays null) was kept —
// i.e. embedding a note could make it start failing this filter. Keyword hits
// are already relevance-filtered by the full-text `@@` match itself, so any
// hit with a non-null keywordScore is trusted regardless of minScore — this is
// also the whole point of hybrid search: an exact-token match (pod name, CRD
// kind, error string) should surface even when its cosine similarity is
// mediocre or it has no embedding in the pool at all.
//
// hybridSearch's SQL applies `LIMIT` (== topK here) BEFORE this filter runs,
// fusing on RRF score — so without over-fetching, a keyword-strong-but-
// vector-weak hit could already be squeezed out of the top-`topK` fused
// results before this function ever sees it, even though it should survive
// the filter. Over-fetch (bounded by HYBRID_CANDIDATE_POOL, the widest either
// leg's own candidate pool goes) and slice to topK after filtering.
//
// minKeywordScore: trusting "any non-null keywordScore" outright (see above)
// means a marginal `ts_rank_cd` hit — one that barely cleared the `@@`
// match threshold, e.g. a single low-weight token appearing once in a long
// note — can unconditionally outrank/displace a strong semantic match and
// makes `minScore` a no-op whenever the keyword leg returns anything at
// all (regression class of #717). `ts_rank_cd` values aren't bounded to
// [0,1] the way cosine similarity is, so this can't share `minScore`'s
// scale; like `minScore` itself, it's uncalibrated against real data (no
// live/dev DB reachable from this change) — 0.01 is a conservative floor
// that only screens out near-zero noise, not a tuned relevance cutoff.
const DEFAULT_MIN_KEYWORD_SCORE = 0.01

/**
 * Filter fused hybrid-search hits down to ones that clear a relevance
 * threshold on whichever leg(s) matched them. Exported standalone (rather
 * than left inline in retrieveKnowledgeContext) so it can be exercised
 * directly in tests against synthetic rows.
 */
export function filterRelevantHits(
  hits: HybridSearchHit[],
  minScore: number,
  minKeywordScore: number = DEFAULT_MIN_KEYWORD_SCORE,
): HybridSearchHit[] {
  return hits.filter(
    h =>
      (h.keywordScore !== null && h.keywordScore >= minKeywordScore) ||
      (h.vectorScore != null && h.vectorScore >= minScore),
  )
}

export async function retrieveKnowledgeContext(
  query: string,
  topK = 3,
  minScore = 0.2,
  minKeywordScore = DEFAULT_MIN_KEYWORD_SCORE,
  callerId?: string,
): Promise<string> {
  try {
    // This function applies no `type` filter, so — unlike its name/original
    // intent might suggest — it doesn't only surface `llm-context` notes; it
    // hybrid-searches the entire Note table. `llm-context` notes (written by
    // worker.ts's writeTaskOutcome) are created with no `createdBy`, i.e.
    // `createdBy: null`, so they're "shared" under ownerFilterSql's semantics
    // and always visible regardless of `callerId`. Passing the real caller's
    // id (when one exists — an ordinary per-user chat request) is therefore
    // both safe (shared/llm-context notes still surface) and required (it's
    // the only thing that prevents another user's private notes from being
    // injected into this user's prompt). `callerId` stays `undefined` for
    // internal/agent-driven callers (worker.ts, agent-context.ts's room-agent
    // pre-flight) that have no single human caller to scope to — see
    // ownerFilterSql's doc comment.
    const fetchLimit = Math.min(topK * 4, HYBRID_CANDIDATE_POOL)
    const { hits } = await hybridSearch(query, fetchLimit, callerId)
    const relevant = filterRelevantHits(hits, minScore, minKeywordScore).slice(0, topK)
    if (relevant.length === 0) return ''

    // Sanitize all retrieved notes before injecting into agent system prompts.
    // Previously this path applied no sanitization — dream-extracted notes and
    // any user-authored note could inject instructions via vector search.
    return relevant
      .map(h => {
        const typeTag = h.type !== 'note' ? ` [${h.type}]` : ''
        const sanitizedContent = sanitizeContextNote(h.title, h.content)
        const body = sanitizedContent.length > 1500
          ? sanitizedContent.slice(0, 1500) + '\n[…]'
          : sanitizedContent
        return `### ${h.title}${typeTag}\n${body}`
      })
      .join('\n\n')
  } catch {
    return ''
  }
}

/**
 * Compute semantic edges for ALL notes. For initial backfill.
 */
export async function computeAllSemanticEdges(topN: number = 5): Promise<{
  computed: number
  failed: number
}> {
  const embeddings = await prisma.noteEmbedding.findMany({
    select: { noteId: true },
  })

  let computed = 0
  let failed = 0

  for (const emb of embeddings) {
    try {
      await computeSemanticEdges(emb.noteId, topN)
      computed++
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      console.error(`computeSemanticEdges(${emb.noteId}) failed: ${msg}`)
      failed++
    }
  }

  return { computed, failed }
}
